import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Layout } from "../components/Layout";
import { HomePage } from "../components/_Pages/Home";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <Layout title="Flexit" description="Generated by create next app">
      <HomePage />
    </Layout>
  );
};

export default Home
