const API_KEY = process.env.NEXT_PUBLIC_API_KEY;

const EMAIL = process.env.NEXT_PUBLIC_EMAIL;

const EMAIL_PASSWORD = process.env.NEXT_PUBLIC_EMAIL_PASSWORD;

const INCOMING_SERVER = process.env.NEXT_PUBLIC_INCOMING_SERVER;

const SMTP_PORT = process.env.NEXT_PUBLIC_SMTP_PORT;

export { API_KEY, EMAIL, EMAIL_PASSWORD, INCOMING_SERVER, SMTP_PORT };
